[profile.default]
src = 'contracts'
out = 'out'

fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_goerli = "${BASE_GOERLI_RPC_URL}"
tenderly = "${TENDERLY_RPC_URL}"

[etherscan]
base = { key = "${BASE_SCAN_API_KEY}", url = "${BASE_ETHERSCAN_VERIFIER_URL}" }
base_goerli = { key = "${BASE_GOERLI_SCAN_API_KEY}", url = "${BASE_GOERLI_ETHERSCAN_VERIFIER_URL}" }
